<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>InstallerUI</AssemblyName>
    <RootNamespace>InstallerUI</RootNamespace>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WixToolset.BootstrapperApplicationApi" Version="5.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\Package2\Assets\banner.png" Link="Assets\banner.png" />
    <Resource Include="..\Package2\Assets\logo.jpg" Link="Assets\logo.jpg" />
    <Resource Include="Assets\Eula.rtf" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Pages\BasePage.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

</Project>
